[package]
name = "beatble"
version = "0.1.0"
authors = ["watiko <service@mail.watiko.net>"]
license = "MIT"
edition = "2021"

[dependencies]
bitflags = "1.3"
# bluster = "0.1.4"
bluster = { git = "https://github.com/dfrankland/bluster", rev = "aa886ad3fbde73df07f7d0c1de11efbd51a8f41e" }
clap = { version = "3", features = ["derive"] }
crossbeam = "0.8"
env_logger = "0.9"
eyre = "0.6"
futures = "0.3"
log = "0.4"
nix = "0.23"
thiserror = "1.0"
tokio = { version = "1", features = ["full"] }
uuid = "0.8"

[package.metadata.deb]
depends = "udev, systemd"
assets = [
  ["target/release/beatble", "usr/bin/", "755"],
  ["assets/udev/*", "etc/udev/rules.d/", "644"],
  ["assets/systemd/*", "etc/systemd/system/", "644"],
]

